// Generated by scripts/generate-design-tokens.mjs — do not edit by hand.
// Source of truth: design/faithful/tokens.json
// Regenerate with: pnpm design:generate

package io.faithform.faithful.design

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit

/**
 * Canonical Faithful design tokens.
 *
 * Values come from `design/faithful/tokens.json`. Editing them here has no
 * effect beyond the next regeneration, and CI fails on drift.
 */
object FaithfulTokens {
    const val VERSION = "1.0.0"

    data class Palette(
        val brandPrimary: Color,
        val brandAccent: Color,
        val brandAccentSoft: Color,
        val background: Color,
        val surface: Color,
        val surfaceRaised: Color,
        val surfaceSunken: Color,
        val surfaceInverse: Color,
        val contentPrimary: Color,
        val contentSecondary: Color,
        val contentMuted: Color,
        val contentInverse: Color,
        val contentOnAccent: Color,
        val border: Color,
        val borderStrong: Color,
        val divider: Color,
        val destructive: Color,
        val destructiveContent: Color,
        val success: Color,
        val successContent: Color,
        val warning: Color,
        val warningContent: Color,
        val live: Color,
        val liveContent: Color,
        val focusRing: Color,
        val overlayScrim: Color,
        val skeletonBase: Color,
        val skeletonSheen: Color
    )

    val LIGHT = Palette(
        brandPrimary = Color(0xFF002D5F),
        brandAccent = Color(0xFFC5A059),
        brandAccentSoft = Color(0xFFEBAA5F),
        background = Color(0xFFF8F7F4),
        surface = Color(0xFFFFFFFF),
        surfaceRaised = Color(0xFFFFFFFF),
        surfaceSunken = Color(0xFFF0EDE6),
        surfaceInverse = Color(0xFF002D5F),
        contentPrimary = Color(0xFF002D5F),
        contentSecondary = Color(0xFF4A5568),
        contentMuted = Color(0xFF6B7280),
        contentInverse = Color(0xFFFFFFFF),
        contentOnAccent = Color(0xFF002D5F),
        border = Color(0xFFDDD9D0),
        borderStrong = Color(0xFFC4BFB4),
        divider = Color(0xFFEAE7E0),
        destructive = Color(0xFFB42318),
        destructiveContent = Color(0xFFFFFFFF),
        success = Color(0xFF0F7B4F),
        successContent = Color(0xFFFFFFFF),
        warning = Color(0xFFB54708),
        warningContent = Color(0xFFFFFFFF),
        live = Color(0xFFD92D20),
        liveContent = Color(0xFFFFFFFF),
        focusRing = Color(0xFFC5A059),
        overlayScrim = Color(0x29002D5F),
        skeletonBase = Color(0xFFEAE7E0),
        skeletonSheen = Color(0xFFF5F3EF)
    )

    val DARK = Palette(
        brandPrimary = Color(0xFFC5A059),
        brandAccent = Color(0xFFC5A059),
        brandAccentSoft = Color(0xFFEBAA5F),
        background = Color(0xFF0A1628),
        surface = Color(0xFF0F2040),
        surfaceRaised = Color(0xFF16294B),
        surfaceSunken = Color(0xFF061020),
        surfaceInverse = Color(0xFFF0EDE6),
        contentPrimary = Color(0xFFF0EDE6),
        contentSecondary = Color(0xFFC3CAD6),
        contentMuted = Color(0xFF9CA3AF),
        contentInverse = Color(0xFF002D5F),
        contentOnAccent = Color(0xFF002D5F),
        border = Color(0xFF22375E),
        borderStrong = Color(0xFF33507F),
        divider = Color(0xFF1A3560),
        destructive = Color(0xFFF97066),
        destructiveContent = Color(0xFF2A0907),
        success = Color(0xFF4ADE80),
        successContent = Color(0xFF04240F),
        warning = Color(0xFFFDB022),
        warningContent = Color(0xFF2B1804),
        live = Color(0xFFF97066),
        liveContent = Color(0xFF2A0907),
        focusRing = Color(0xFFEBAA5F),
        overlayScrim = Color(0xA300060F),
        skeletonBase = Color(0xFF16294B),
        skeletonSheen = Color(0xFF1E3457)
    )

    object Spacing {
        val xs: Dp = 4.dp
        val sm: Dp = 8.dp
        val md: Dp = 12.dp
        val base: Dp = 16.dp
        val lg: Dp = 24.dp
        val xl: Dp = 32.dp
        val xxl: Dp = 48.dp
        val xxxl: Dp = 64.dp
    }

    object Radius {
        val none: Dp = 0.dp
        val sm: Dp = 8.dp
        val md: Dp = 12.dp
        val lg: Dp = 16.dp
        val xl: Dp = 24.dp
        val pill: Dp = 999.dp
    }

    object Layout {
        val screenPaddingHorizontal: Dp = 20.dp
        val screenPaddingVertical: Dp = 16.dp
        val contentMaxWidth: Dp = 640.dp
        val sectionGap: Dp = 32.dp
        val listItemGap: Dp = 12.dp
        val gridGutter: Dp = 16.dp
    }

    object BorderWidth {
        val hairline: Dp = 1.dp
        val standard: Dp = 1.5.dp
        val emphasis: Dp = 2.dp
    }

    object IconSize {
        val sizeSmall: Dp = 16.dp
        val sizeMedium: Dp = 20.dp
        val sizeLarge: Dp = 24.dp
        val sizeHero: Dp = 32.dp
        val strokeWidth: Dp = 1.75.dp
    }

    object TouchTarget {
        val minimum: Dp = 44.dp
        val recommended: Dp = 48.dp
    }

    data class TextRole(
        val size: TextUnit,
        val lineHeight: TextUnit,
        val weight: FontWeight,
        val trackingSp: Double,
        val isDisplay: Boolean
    )

    object Text {
        val displayLarge = TextRole(34.sp, 40.sp, FontWeight(600), -0.40, true)
        val displayMedium = TextRole(28.sp, 34.sp, FontWeight(600), -0.30, true)
        val titleLarge = TextRole(22.sp, 28.sp, FontWeight(600), -0.20, false)
        val titleMedium = TextRole(17.sp, 24.sp, FontWeight(600), 0.00, false)
        val body = TextRole(17.sp, 26.sp, FontWeight(400), 0.00, false)
        val bodySmall = TextRole(15.sp, 22.sp, FontWeight(400), 0.00, false)
        val label = TextRole(13.sp, 18.sp, FontWeight(600), 0.20, false)
        val caption = TextRole(12.sp, 16.sp, FontWeight(400), 0.20, false)
    }

    object Motion {
        const val INSTANT_MS = 0
        const val FAST_MS = 120
        const val STANDARD_MS = 220
        const val SLOW_MS = 320
        const val DELIBERATE_MS = 480
        const val REDUCED_MOTION_MS = 100
    }

    object Elevation {
        val noneY: Dp = 0.dp
        val noneBlur: Dp = 0.dp
        const val NONE_OPACITY = 0.00f
        val raisedY: Dp = 1.dp
        val raisedBlur: Dp = 3.dp
        const val RAISED_OPACITY = 0.06f
        val cardY: Dp = 4.dp
        val cardBlur: Dp = 12.dp
        const val CARD_OPACITY = 0.08f
        val sheetY: Dp = 8.dp
        val sheetBlur: Dp = 28.dp
        const val SHEET_OPACITY = 0.14f
    }
}
