import type { SiteThemeDefinition } from "@/lib/sites/themes/types";

/**
 * Code copies of the formats seeded by migration 0042, for the dev preview
 * (`/dev-site-preview/<key>`) and tests. The database row is what production
 * renders; `tests/unit/site-themes.test.ts` keeps these from drifting.
 */
export const graceTheme: SiteThemeDefinition = {
  key: "grace",
  name: "Grace",
  description:
    "Contemporary and warm. Deep indigo over cream, pale-blue accent, oversized display type with a serif italic counterpoint.",
  tokens: {
    "--site-ink": "#2E2B46",
    "--site-ink-strong": "#26233b",
    "--site-ink-soft": "#33304d",
    "--site-accent": "#AED8F5",
    "--site-accent-ink": "#2E2B46",
    "--site-canvas": "#f6f4ee",
    "--site-canvas-alt": "#efece4",
    "--site-gold": "#8f7a52",
    "--site-body": "#5a5770",
    "--site-muted": "#7a7690",
    "--site-muted-soft": "#8a86a0",
    "--site-surface": "#ffffff",
    "--site-font-display": "'Bricolage Grotesque', system-ui, sans-serif",
    "--site-font-body": "'Instrument Sans', system-ui, sans-serif",
    "--site-font-accent": "'Newsreader', Georgia, serif",
    "--site-radius-card": "18px",
    "--site-radius-btn": "8px",
    "--site-radius-panel": "22px",
    "--site-section-y": "96px",
    "--site-section-x": "46px",
    "--site-display-xl": "116px",
    "--site-display-lg": "50px",
    "--site-display-md": "46px",
    "--site-heading-tracking": "-0.025em",
    "--site-max-width": "1280px",
  },
  sectionDefaults: {
    hero: { surface: "ink", align: "split" },
    service_times: { surface: "ink", columns: 4 },
    about_text: { surface: "canvas", align: "split" },
    vision_mission: { surface: "ink", align: "center" },
    staff_grid: { surface: "canvas-alt", align: "split", columns: 4 },
    programs_grid: { surface: "ink", align: "split", columns: 3 },
    events_list: { surface: "canvas", align: "split" },
    visit_cta: { surface: "accent" },
    sermon_feed: { surface: "ink", align: "split" },
    give_cta: { surface: "canvas" },
    contact_band: { surface: "ink" },
    footer_map: { surface: "ink-strong" },
  },
};

export const classicTheme: SiteThemeDefinition = {
  key: "classic",
  name: "Classic",
  description:
    "Traditional and restrained. Ivory over deep green, gold accent, centred section headers and tighter display type.",
  tokens: {
    "--site-ink": "#1F3B2C",
    "--site-ink-strong": "#16291F",
    "--site-ink-soft": "#2C4A39",
    "--site-accent": "#C9A227",
    "--site-accent-ink": "#16291F",
    "--site-canvas": "#FBF9F4",
    "--site-canvas-alt": "#F2EEE4",
    "--site-gold": "#8A6D2F",
    "--site-body": "#4A5A50",
    "--site-muted": "#6E7C73",
    "--site-muted-soft": "#8A968E",
    "--site-surface": "#ffffff",
    "--site-font-display": "'Newsreader', Georgia, serif",
    "--site-font-body": "'Instrument Sans', system-ui, sans-serif",
    "--site-font-accent": "'Newsreader', Georgia, serif",
    "--site-radius-card": "6px",
    "--site-radius-btn": "4px",
    "--site-radius-panel": "8px",
    "--site-section-y": "84px",
    "--site-section-x": "46px",
    "--site-display-xl": "82px",
    "--site-display-lg": "42px",
    "--site-display-md": "38px",
    "--site-heading-tracking": "-0.01em",
    "--site-max-width": "1180px",
  },
  sectionDefaults: {
    hero: { surface: "ink", align: "center" },
    service_times: { surface: "ink", columns: 3 },
    about_text: { surface: "canvas", align: "center" },
    vision_mission: { surface: "canvas-alt", align: "center" },
    staff_grid: { surface: "canvas", align: "center", columns: 3 },
    programs_grid: { surface: "canvas-alt", align: "center", columns: 3 },
    events_list: { surface: "canvas", align: "center" },
    visit_cta: { surface: "ink" },
    sermon_feed: { surface: "canvas", align: "center" },
    give_cta: { surface: "canvas-alt" },
    contact_band: { surface: "ink" },
    footer_map: { surface: "ink-strong" },
  },
};
