// Generated by scripts/generate-contract.mjs — do not edit by hand.
// Source of truth: lib/mobile/v1/contract.ts
// Regenerate with: pnpm contract:generate

package io.faithform.faithful.contract

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class RelationshipState {
    @SerialName("following") FOLLOWING,
    @SerialName("pending") PENDING,
    @SerialName("joined") JOINED,
    @SerialName("left") LEFT,
    @SerialName("blocked") BLOCKED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): RelationshipState =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            FOLLOWING -> "following"
            PENDING -> "pending"
            JOINED -> "joined"
            LEFT -> "left"
            BLOCKED -> "blocked"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class JoinPolicy {
    @SerialName("open") OPEN,
    @SerialName("approval_required") APPROVAL_REQUIRED,
    @SerialName("invite_only") INVITE_ONLY,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): JoinPolicy =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            OPEN -> "open"
            APPROVAL_REQUIRED -> "approval_required"
            INVITE_ONLY -> "invite_only"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class ConsentState {
    @SerialName("unset") UNSET,
    @SerialName("granted") GRANTED,
    @SerialName("denied") DENIED,
    @SerialName("revoked") REVOKED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): ConsentState =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            UNSET -> "unset"
            GRANTED -> "granted"
            DENIED -> "denied"
            REVOKED -> "revoked"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class AccountStatus {
    @SerialName("active") ACTIVE,
    @SerialName("deactivated") DEACTIVATED,
    @SerialName("deletion_requested") DELETION_REQUESTED,
    @SerialName("deleted") DELETED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): AccountStatus =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            ACTIVE -> "active"
            DEACTIVATED -> "deactivated"
            DELETION_REQUESTED -> "deletion_requested"
            DELETED -> "deleted"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class AccountRequestKind {
    @SerialName("export") EXPORT,
    @SerialName("deletion") DELETION,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): AccountRequestKind =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            EXPORT -> "export"
            DELETION -> "deletion"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class AccountRequestStatus {
    @SerialName("pending") PENDING,
    @SerialName("processing") PROCESSING,
    @SerialName("completed") COMPLETED,
    @SerialName("failed") FAILED,
    @SerialName("cancelled") CANCELLED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): AccountRequestStatus =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            PENDING -> "pending"
            PROCESSING -> "processing"
            COMPLETED -> "completed"
            FAILED -> "failed"
            CANCELLED -> "cancelled"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class MobileErrorCode {
    @SerialName("invalid_request") INVALID_REQUEST,
    @SerialName("invalid_cursor") INVALID_CURSOR,
    @SerialName("missing_idempotency_key") MISSING_IDEMPOTENCY_KEY,
    @SerialName("payload_too_large") PAYLOAD_TOO_LARGE,
    @SerialName("unauthenticated") UNAUTHENTICATED,
    @SerialName("session_expired") SESSION_EXPIRED,
    @SerialName("forbidden") FORBIDDEN,
    @SerialName("blocked") BLOCKED,
    @SerialName("account_inactive") ACCOUNT_INACTIVE,
    @SerialName("not_found") NOT_FOUND,
    @SerialName("conflict") CONFLICT,
    @SerialName("already_linked") ALREADY_LINKED,
    @SerialName("idempotency_key_reused") IDEMPOTENCY_KEY_REUSED,
    @SerialName("invitation_expired") INVITATION_EXPIRED,
    @SerialName("client_version_unsupported") CLIENT_VERSION_UNSUPPORTED,
    @SerialName("stale_version") STALE_VERSION,
    @SerialName("rate_limited") RATE_LIMITED,
    @SerialName("unavailable") UNAVAILABLE,
    @SerialName("internal_error") INTERNAL_ERROR,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): MobileErrorCode =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            INVALID_REQUEST -> "invalid_request"
            INVALID_CURSOR -> "invalid_cursor"
            MISSING_IDEMPOTENCY_KEY -> "missing_idempotency_key"
            PAYLOAD_TOO_LARGE -> "payload_too_large"
            UNAUTHENTICATED -> "unauthenticated"
            SESSION_EXPIRED -> "session_expired"
            FORBIDDEN -> "forbidden"
            BLOCKED -> "blocked"
            ACCOUNT_INACTIVE -> "account_inactive"
            NOT_FOUND -> "not_found"
            CONFLICT -> "conflict"
            ALREADY_LINKED -> "already_linked"
            IDEMPOTENCY_KEY_REUSED -> "idempotency_key_reused"
            INVITATION_EXPIRED -> "invitation_expired"
            CLIENT_VERSION_UNSUPPORTED -> "client_version_unsupported"
            STALE_VERSION -> "stale_version"
            RATE_LIMITED -> "rate_limited"
            UNAVAILABLE -> "unavailable"
            INTERNAL_ERROR -> "internal_error"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class AnnouncementVisibility {
    @SerialName("public") PUBLIC,
    @SerialName("followers") FOLLOWERS,
    @SerialName("members") MEMBERS,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): AnnouncementVisibility =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            PUBLIC -> "public"
            FOLLOWERS -> "followers"
            MEMBERS -> "members"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class NotificationTopic {
    @SerialName("announcements") ANNOUNCEMENTS,
    @SerialName("events") EVENTS,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): NotificationTopic =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            ANNOUNCEMENTS -> "announcements"
            EVENTS -> "events"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class DevicePlatform {
    @SerialName("ios") IOS,
    @SerialName("android") ANDROID,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): DevicePlatform =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            IOS -> "ios"
            ANDROID -> "android"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class AttendanceSource {
    @SerialName("manual") MANUAL,
    @SerialName("admin") ADMIN,
    @SerialName("geofence") GEOFENCE,
    @SerialName("qr") QR,
    @SerialName("kiosk") KIOSK,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): AttendanceSource =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            MANUAL -> "manual"
            ADMIN -> "admin"
            GEOFENCE -> "geofence"
            QR -> "qr"
            KIOSK -> "kiosk"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class AttendanceOutcome {
    @SerialName("counted") COUNTED,
    @SerialName("already_counted") ALREADY_COUNTED,
    @SerialName("pending_confirmation") PENDING_CONFIRMATION,
    @SerialName("rejected") REJECTED,
    @SerialName("reversed") REVERSED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): AttendanceOutcome =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            COUNTED -> "counted"
            ALREADY_COUNTED -> "already_counted"
            PENDING_CONFIRMATION -> "pending_confirmation"
            REJECTED -> "rejected"
            REVERSED -> "reversed"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class MediaKind {
    @SerialName("live") LIVE,
    @SerialName("recording") RECORDING,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): MediaKind =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            LIVE -> "live"
            RECORDING -> "recording"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class MediaRenditionKind {
    @SerialName("hls") HLS,
    @SerialName("progressive") PROGRESSIVE,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): MediaRenditionKind =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            HLS -> "hls"
            PROGRESSIVE -> "progressive"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class LiveMediaState {
    @SerialName("live") LIVE,
    @SerialName("upcoming") UPCOMING,
    @SerialName("recent_ended") RECENT_ENDED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): LiveMediaState =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            LIVE -> "live"
            UPCOMING -> "upcoming"
            RECENT_ENDED -> "recent_ended"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class GivingAvailability {
    @SerialName("available") AVAILABLE,
    @SerialName("not_accepting") NOT_ACCEPTING,
    @SerialName("not_found") NOT_FOUND,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): GivingAvailability =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            AVAILABLE -> "available"
            NOT_ACCEPTING -> "not_accepting"
            NOT_FOUND -> "not_found"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class DonationStatus {
    @SerialName("initiated") INITIATED,
    @SerialName("requires_action") REQUIRES_ACTION,
    @SerialName("processing") PROCESSING,
    @SerialName("succeeded") SUCCEEDED,
    @SerialName("failed") FAILED,
    @SerialName("cancelled") CANCELLED,
    @SerialName("refunded") REFUNDED,
    @SerialName("disputed") DISPUTED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): DonationStatus =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            INITIATED -> "initiated"
            REQUIRES_ACTION -> "requires_action"
            PROCESSING -> "processing"
            SUCCEEDED -> "succeeded"
            FAILED -> "failed"
            CANCELLED -> "cancelled"
            REFUNDED -> "refunded"
            DISPUTED -> "disputed"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class GiftType {
    @SerialName("one_time") ONE_TIME,
    @SerialName("recurring") RECURRING,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): GiftType =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            ONE_TIME -> "one_time"
            RECURRING -> "recurring"
            UNKNOWN -> "unknown"
        }
}

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class Deprecation(
    val sunsetOn: String,
    val replacement: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class FieldIssue(
    val field: String,
    val issue: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class Meta(
    val apiVersion: String,
    val apiMajor: Int,
    val requestId: String,
    val minimumSupportedClientBuild: Int,
    val deprecation: Deprecation? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ErrorBody(
    val code: MobileErrorCode,
    val message: String,
    val retryable: Boolean,
    val fields: List<FieldIssue>? = null,
    val retryAfterSeconds: Int? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class Failure(
    val ok: Boolean,
    val error: ErrorBody,
    val meta: Meta
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class VisitorProfile(
    val displayName: String? = null,
    val avatarUrl: String? = null,
    val status: AccountStatus,
    val termsVersion: String? = null,
    val termsAcceptedAt: String? = null,
    val privacyVersion: String? = null,
    val privacyAcceptedAt: String? = null,
    val autoAttendanceConsent: ConsentState,
    val communicationPrefs: Map<String, Boolean>,
    val selectedChurchSlug: String? = null,
    val authorizationVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChurchRelationship(
    val churchSlug: String,
    val churchName: String,
    val logoUrl: String? = null,
    val state: RelationshipState,
    val joinPolicy: JoinPolicy,
    val joinedAt: String? = null,
    val updatedAt: String,
    val canReadPublishedContent: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AccountRequest(
    val id: String,
    val kind: AccountRequestKind,
    val status: AccountRequestStatus,
    val requestedAt: String,
    val completedAt: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class Bootstrap(
    val profile: VisitorProfile,
    val relationships: List<ChurchRelationship>,
    val pendingRequests: List<AccountRequest>,
    val requiredTermsVersion: String,
    val requiredPrivacyVersion: String,
    val enabledCapabilities: List<String>,
    val serverTime: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class RelationshipPage(
    val items: List<ChurchRelationship>,
    val nextCursor: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SelectedChurch(
    val selectedChurchSlug: String? = null,
    val authorizationVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SignOutResult(
    val signedOut: Boolean,
    val authorizationVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class Health(
    val status: String,
    val apiVersion: String,
    val apiMajor: Int,
    val minimumSupportedClientBuild: Int,
    val serverTime: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class UpdateProfileRequest(
    val displayName: String? = null,
    val communicationPrefs: Map<String, Boolean>? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SelectChurchRequest(
    val churchSlug: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ConsentRequest(
    val termsVersion: String? = null,
    val privacyVersion: String? = null,
    val autoAttendanceConsent: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AccountActionRequest(
    val kind: AccountRequestKind
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class DiscoveredChurch(
    val slug: String,
    val name: String,
    val logoUrl: String? = null,
    val publicSummary: String? = null,
    val denomination: String? = null,
    val city: String? = null,
    val state: String? = null,
    val postalCode: String? = null,
    val joinPolicy: JoinPolicy,
    val publicProfileVersion: Int,
    val distanceKm: Double? = null,
    val campusName: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class DiscoveryPage(
    val items: List<DiscoveredChurch>,
    val nextCursor: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PublicCampus(
    val slug: String,
    val name: String,
    val addressLine1: String? = null,
    val city: String? = null,
    val state: String? = null,
    val postalCode: String? = null,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val timezone: String,
    val isPrimary: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PublicServiceTime(
    val campusSlug: String,
    val label: String,
    val dayOfWeek: Int,
    val startTime: String,
    val kind: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChurchProfile(
    val slug: String,
    val name: String,
    val logoUrl: String? = null,
    val coverImageUrl: String? = null,
    val publicSummary: String? = null,
    val tagline: String? = null,
    val denomination: String? = null,
    val address: String? = null,
    val city: String? = null,
    val state: String? = null,
    val postalCode: String? = null,
    val website: String? = null,
    val phone: String? = null,
    val email: String? = null,
    val joinPolicy: JoinPolicy,
    val timezone: String,
    val publicProfileVersion: Int,
    val campuses: List<PublicCampus>,
    val serviceTimes: List<PublicServiceTime>,
    val relationshipState: RelationshipState? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class OnboardingState(
    val needsOnboarding: Boolean,
    val hasAnyRelationship: Boolean,
    val selectedChurchSlug: String? = null,
    val activeChurchCount: Int,
    val requiresChurchChooser: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class FeedItem(
    val id: String,
    val title: String,
    val body: String,
    val startAt: String,
    val endAt: String? = null,
    val location: String? = null,
    val posterUrl: String? = null,
    val posterAltText: String? = null,
    val isPinned: Boolean,
    val visibility: AnnouncementVisibility,
    val publicationVersion: Int,
    val publishedAt: String? = null,
    val isEvent: Boolean,
    val churchSlug: String,
    val churchName: String,
    val churchTimezone: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class FeedPage(
    val items: List<FeedItem>,
    val nextCursor: String? = null,
    val feedVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class NotificationPreference(
    val churchSlug: String,
    val topic: NotificationTopic,
    val isEnabled: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class DeviceInstallation(
    val installId: String,
    val platform: DevicePlatform,
    val isEnabled: Boolean,
    val lastSeenAt: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class FollowRequest(
    val churchSlug: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AcceptInvitationRequest(
    val token: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class RegisterDeviceRequest(
    val installId: String,
    val platform: DevicePlatform,
    val provider: String,
    val providerToken: String,
    val appVersion: String? = null,
    val clientBuild: Int? = null,
    val osVersion: String? = null,
    val locale: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SetPreferenceRequest(
    val churchSlug: String,
    val topic: NotificationTopic,
    val isEnabled: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class EligibleOccurrence(
    val occurrenceId: String,
    val label: String,
    val churchSlug: String,
    val campusName: String? = null,
    val localServiceDate: String,
    val timezone: String,
    val startsAt: String,
    val endsAt: String,
    val checkinOpensAt: String,
    val checkinClosesAt: String,
    val status: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceCapability(
    val occurrenceId: String,
    val geofenceEnabled: Boolean,
    val qrEnabled: Boolean,
    val manualEnabled: Boolean,
    val requiresConfirmation: Boolean,
    val minDwellSeconds: Int,
    val maxLocationAccuracyM: Int,
    val hasVerifiedPeopleLink: Boolean,
    val autoAttendanceConsent: ConsentState,
    val canAttemptAutomatically: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceResult(
    val outcome: AttendanceOutcome,
    val message: String,
    val occurrenceId: String? = null,
    val countedAt: String? = null,
    val confirmationNotBefore: String? = null,
    val detectionId: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceStatus(
    val occurrenceId: String,
    val isCounted: Boolean,
    val status: String? = null,
    val source: AttendanceSource? = null,
    val countedAt: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceHistoryItem(
    val occurrenceId: String,
    val label: String,
    val localServiceDate: String,
    val campusName: String? = null,
    val source: AttendanceSource,
    val status: String,
    val countedAt: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceHistoryPage(
    val items: List<AttendanceHistoryItem>,
    val nextCursor: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceAttemptRequest(
    val occurrenceId: String? = null,
    val source: String,
    val phase: String,
    val observedAt: String? = null,
    val accuracyMeters: Double? = null,
    val dwellSeconds: Int? = null,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val mockLocationReported: Boolean? = null,
    val attemptId: String? = null,
    val detectionId: String? = null,
    val regionId: String? = null,
    val configVersion: Int? = null,
    val qrToken: String? = null,
    val shortCode: String? = null,
    val scanAttemptId: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceConsentRequest(
    val autoAttendanceConsent: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceConsentResult(
    val autoAttendanceConsent: String,
    val authorizationVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GeofenceRegion(
    val regionId: String,
    val campusName: String,
    val latitude: Double,
    val longitude: Double,
    val radiusMeters: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GeofenceWindow(
    val occurrenceId: String,
    val label: String,
    val startsAt: String,
    val endsAt: String,
    val checkinOpensAt: String,
    val checkinClosesAt: String,
    val timezone: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceSourceAvailability(
    val geofence: Boolean,
    val qr: Boolean,
    val manual: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GeofenceConfiguration(
    val churchSlug: String,
    val regions: List<GeofenceRegion>,
    val windows: List<GeofenceWindow>,
    val sources: AttendanceSourceAvailability,
    val requiresConfirmation: Boolean,
    val minDwellSeconds: Int,
    val maxLocationAccuracyM: Int,
    val configVersion: Int,
    val expiresAt: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GeofenceConfigResponse(
    val configuration: GeofenceConfiguration? = null,
    val refusalReason: String? = null,
    val message: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class LiveMedia(
    val state: String,
    val mediaId: String,
    val kind: String,
    val title: String,
    val startsAt: String,
    val countdownEnabled: Boolean,
    val posterUrl: String? = null,
    val publicationVersion: Int,
    val churchSlug: String,
    val churchName: String,
    val churchTimezone: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class LiveMediaResponse(
    val live: LiveMedia? = null,
    val mediaVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ArchiveItem(
    val mediaId: String,
    val kind: String,
    val title: String,
    val summary: String? = null,
    val publishedAt: String,
    val recordedAt: String,
    val durationSeconds: Int? = null,
    val posterUrl: String? = null,
    val seriesName: String? = null,
    val speakers: List<String>,
    val publicationVersion: Int,
    val churchSlug: String,
    val churchName: String,
    val churchTimezone: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class MediaPage(
    val items: List<ArchiveItem>,
    val nextCursor: String? = null,
    val mediaVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class MediaDetail(
    val mediaId: String,
    val kind: String,
    val title: String,
    val summary: String? = null,
    val publishedAt: String,
    val recordedAt: String,
    val durationSeconds: Int? = null,
    val startOffsetSeconds: Int,
    val posterUrl: String? = null,
    val seriesName: String? = null,
    val speakers: List<String>,
    val chapters: List<String>,
    val topics: List<String>,
    val publicationVersion: Int,
    val churchSlug: String,
    val churchName: String,
    val churchTimezone: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PlaybackGrant(
    val capability: String,
    val expiresAt: String,
    val deliveryUrl: String,
    val kind: String,
    val renditionKind: String,
    val mediaId: String,
    val refreshAfterSeconds: Int,
    val startOffsetSeconds: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PlaybackGrantRequest(
    val churchSlug: String,
    val kind: String,
    val mediaId: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GivingFund(
    val fundId: String,
    val title: String,
    val description: String? = null,
    val suggestedAmounts: List<Int>,
    val minAmountCents: Int,
    val maxAmountCents: Int,
    val currency: String,
    val publicationVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GivingHome(
    val availability: String,
    val churchName: String? = null,
    val funds: List<GivingFund>,
    val recurringAvailable: Boolean,
    val givingVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class StartDonationRequest(
    val churchSlug: String,
    val fundId: String,
    val amountCents: Int,
    val clientAttemptId: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class DonationSession(
    val attemptId: String,
    val status: String,
    val clientSecret: String,
    val publishableKey: String,
    val stripeAccountId: String,
    val merchantName: String,
    val amountCents: Int,
    val currency: String,
    val fundTitle: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class DonationStatusResult(
    val attemptId: String,
    val status: String,
    val amountCents: Int,
    val currency: String,
    val fundTitle: String,
    val confirmed: Boolean,
    val occurredAt: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GivingHistoryPage(
    val items: List<DonationStatusResult>,
    val nextCursor: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GivingReceipt(
    val attemptId: String,
    val amountCents: Int,
    val currency: String,
    val fundTitle: String,
    val churchName: String,
    val paidAt: String,
    val giftType: String
)

