// Generated by scripts/generate-contract.mjs — do not edit by hand.
// Source of truth: lib/mobile/v1/contract.ts
// Regenerate with: pnpm contract:generate

package io.faithform.app.contract

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class RelationshipState {
    @SerialName("following") FOLLOWING,
    @SerialName("pending") PENDING,
    @SerialName("joined") JOINED,
    @SerialName("left") LEFT,
    @SerialName("blocked") BLOCKED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): RelationshipState =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            FOLLOWING -> "following"
            PENDING -> "pending"
            JOINED -> "joined"
            LEFT -> "left"
            BLOCKED -> "blocked"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class JoinPolicy {
    @SerialName("open") OPEN,
    @SerialName("approval_required") APPROVAL_REQUIRED,
    @SerialName("invite_only") INVITE_ONLY,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): JoinPolicy =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            OPEN -> "open"
            APPROVAL_REQUIRED -> "approval_required"
            INVITE_ONLY -> "invite_only"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class ConsentState {
    @SerialName("unset") UNSET,
    @SerialName("granted") GRANTED,
    @SerialName("denied") DENIED,
    @SerialName("revoked") REVOKED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): ConsentState =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            UNSET -> "unset"
            GRANTED -> "granted"
            DENIED -> "denied"
            REVOKED -> "revoked"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class AccountStatus {
    @SerialName("active") ACTIVE,
    @SerialName("deactivated") DEACTIVATED,
    @SerialName("deletion_requested") DELETION_REQUESTED,
    @SerialName("deleted") DELETED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): AccountStatus =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            ACTIVE -> "active"
            DEACTIVATED -> "deactivated"
            DELETION_REQUESTED -> "deletion_requested"
            DELETED -> "deleted"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class AccountRequestKind {
    @SerialName("export") EXPORT,
    @SerialName("deletion") DELETION,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): AccountRequestKind =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            EXPORT -> "export"
            DELETION -> "deletion"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class AccountRequestStatus {
    @SerialName("pending") PENDING,
    @SerialName("processing") PROCESSING,
    @SerialName("completed") COMPLETED,
    @SerialName("failed") FAILED,
    @SerialName("cancelled") CANCELLED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): AccountRequestStatus =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            PENDING -> "pending"
            PROCESSING -> "processing"
            COMPLETED -> "completed"
            FAILED -> "failed"
            CANCELLED -> "cancelled"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class MobileErrorCode {
    @SerialName("invalid_request") INVALID_REQUEST,
    @SerialName("invalid_cursor") INVALID_CURSOR,
    @SerialName("missing_idempotency_key") MISSING_IDEMPOTENCY_KEY,
    @SerialName("payload_too_large") PAYLOAD_TOO_LARGE,
    @SerialName("unauthenticated") UNAUTHENTICATED,
    @SerialName("session_expired") SESSION_EXPIRED,
    @SerialName("forbidden") FORBIDDEN,
    @SerialName("blocked") BLOCKED,
    @SerialName("account_inactive") ACCOUNT_INACTIVE,
    @SerialName("not_found") NOT_FOUND,
    @SerialName("conflict") CONFLICT,
    @SerialName("already_linked") ALREADY_LINKED,
    @SerialName("idempotency_key_reused") IDEMPOTENCY_KEY_REUSED,
    @SerialName("invitation_expired") INVITATION_EXPIRED,
    @SerialName("client_version_unsupported") CLIENT_VERSION_UNSUPPORTED,
    @SerialName("stale_version") STALE_VERSION,
    @SerialName("rate_limited") RATE_LIMITED,
    @SerialName("unavailable") UNAVAILABLE,
    @SerialName("internal_error") INTERNAL_ERROR,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): MobileErrorCode =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            INVALID_REQUEST -> "invalid_request"
            INVALID_CURSOR -> "invalid_cursor"
            MISSING_IDEMPOTENCY_KEY -> "missing_idempotency_key"
            PAYLOAD_TOO_LARGE -> "payload_too_large"
            UNAUTHENTICATED -> "unauthenticated"
            SESSION_EXPIRED -> "session_expired"
            FORBIDDEN -> "forbidden"
            BLOCKED -> "blocked"
            ACCOUNT_INACTIVE -> "account_inactive"
            NOT_FOUND -> "not_found"
            CONFLICT -> "conflict"
            ALREADY_LINKED -> "already_linked"
            IDEMPOTENCY_KEY_REUSED -> "idempotency_key_reused"
            INVITATION_EXPIRED -> "invitation_expired"
            CLIENT_VERSION_UNSUPPORTED -> "client_version_unsupported"
            STALE_VERSION -> "stale_version"
            RATE_LIMITED -> "rate_limited"
            UNAVAILABLE -> "unavailable"
            INTERNAL_ERROR -> "internal_error"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class AnnouncementVisibility {
    @SerialName("public") PUBLIC,
    @SerialName("followers") FOLLOWERS,
    @SerialName("members") MEMBERS,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): AnnouncementVisibility =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            PUBLIC -> "public"
            FOLLOWERS -> "followers"
            MEMBERS -> "members"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class NotificationTopic {
    @SerialName("announcements") ANNOUNCEMENTS,
    @SerialName("events") EVENTS,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): NotificationTopic =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            ANNOUNCEMENTS -> "announcements"
            EVENTS -> "events"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class DevicePlatform {
    @SerialName("ios") IOS,
    @SerialName("android") ANDROID,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): DevicePlatform =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            IOS -> "ios"
            ANDROID -> "android"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class AttendanceSource {
    @SerialName("manual") MANUAL,
    @SerialName("admin") ADMIN,
    @SerialName("geofence") GEOFENCE,
    @SerialName("qr") QR,
    @SerialName("kiosk") KIOSK,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): AttendanceSource =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            MANUAL -> "manual"
            ADMIN -> "admin"
            GEOFENCE -> "geofence"
            QR -> "qr"
            KIOSK -> "kiosk"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class AttendanceOutcome {
    @SerialName("counted") COUNTED,
    @SerialName("already_counted") ALREADY_COUNTED,
    @SerialName("pending_confirmation") PENDING_CONFIRMATION,
    @SerialName("rejected") REJECTED,
    @SerialName("reversed") REVERSED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): AttendanceOutcome =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            COUNTED -> "counted"
            ALREADY_COUNTED -> "already_counted"
            PENDING_CONFIRMATION -> "pending_confirmation"
            REJECTED -> "rejected"
            REVERSED -> "reversed"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class MediaKind {
    @SerialName("live") LIVE,
    @SerialName("recording") RECORDING,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): MediaKind =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            LIVE -> "live"
            RECORDING -> "recording"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class MediaRenditionKind {
    @SerialName("hls") HLS,
    @SerialName("progressive") PROGRESSIVE,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): MediaRenditionKind =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            HLS -> "hls"
            PROGRESSIVE -> "progressive"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class LiveMediaState {
    @SerialName("live") LIVE,
    @SerialName("upcoming") UPCOMING,
    @SerialName("recent_ended") RECENT_ENDED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): LiveMediaState =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            LIVE -> "live"
            UPCOMING -> "upcoming"
            RECENT_ENDED -> "recent_ended"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class GivingAvailability {
    @SerialName("available") AVAILABLE,
    @SerialName("not_accepting") NOT_ACCEPTING,
    @SerialName("not_found") NOT_FOUND,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): GivingAvailability =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            AVAILABLE -> "available"
            NOT_ACCEPTING -> "not_accepting"
            NOT_FOUND -> "not_found"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class DonationStatus {
    @SerialName("initiated") INITIATED,
    @SerialName("requires_action") REQUIRES_ACTION,
    @SerialName("processing") PROCESSING,
    @SerialName("succeeded") SUCCEEDED,
    @SerialName("failed") FAILED,
    @SerialName("cancelled") CANCELLED,
    @SerialName("refunded") REFUNDED,
    @SerialName("disputed") DISPUTED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): DonationStatus =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            INITIATED -> "initiated"
            REQUIRES_ACTION -> "requires_action"
            PROCESSING -> "processing"
            SUCCEEDED -> "succeeded"
            FAILED -> "failed"
            CANCELLED -> "cancelled"
            REFUNDED -> "refunded"
            DISPUTED -> "disputed"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class GiftType {
    @SerialName("one_time") ONE_TIME,
    @SerialName("recurring") RECURRING,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): GiftType =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            ONE_TIME -> "one_time"
            RECURRING -> "recurring"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class GivingInterval {
    @SerialName("week") WEEK,
    @SerialName("month") MONTH,
    @SerialName("year") YEAR,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): GivingInterval =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            WEEK -> "week"
            MONTH -> "month"
            YEAR -> "year"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class RecurringGiftStatus {
    @SerialName("active") ACTIVE,
    @SerialName("trialing") TRIALING,
    @SerialName("past_due") PAST_DUE,
    @SerialName("paused") PAUSED,
    @SerialName("unpaid") UNPAID,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): RecurringGiftStatus =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            ACTIVE -> "active"
            TRIALING -> "trialing"
            PAST_DUE -> "past_due"
            PAUSED -> "paused"
            UNPAID -> "unpaid"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class GroupRole {
    @SerialName("member") MEMBER,
    @SerialName("leader") LEADER,
    @SerialName("manager") MANAGER,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): GroupRole =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            MEMBER -> "member"
            LEADER -> "leader"
            MANAGER -> "manager"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class GroupMembershipState {
    @SerialName("member") MEMBER,
    @SerialName("requested") REQUESTED,
    @SerialName("invited") INVITED,
    @SerialName("not_member") NOT_MEMBER,
    @SerialName("banned") BANNED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): GroupMembershipState =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            MEMBER -> "member"
            REQUESTED -> "requested"
            INVITED -> "invited"
            NOT_MEMBER -> "not_member"
            BANNED -> "banned"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class GroupJoinAction {
    @SerialName("join") JOIN,
    @SerialName("request") REQUEST,
    @SerialName("cancel_request") CANCEL_REQUEST,
    @SerialName("leave") LEAVE,
    @SerialName("invitation_required") INVITATION_REQUIRED,
    @SerialName("full") FULL,
    @SerialName("closed") CLOSED,
    @SerialName("unavailable") UNAVAILABLE,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): GroupJoinAction =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            JOIN -> "join"
            REQUEST -> "request"
            CANCEL_REQUEST -> "cancel_request"
            LEAVE -> "leave"
            INVITATION_REQUIRED -> "invitation_required"
            FULL -> "full"
            CLOSED -> "closed"
            UNAVAILABLE -> "unavailable"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class GroupEnrollment {
    @SerialName("open") OPEN,
    @SerialName("approval_required") APPROVAL_REQUIRED,
    @SerialName("invitation_only") INVITATION_ONLY,
    @SerialName("closed") CLOSED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): GroupEnrollment =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            OPEN -> "open"
            APPROVAL_REQUIRED -> "approval_required"
            INVITATION_ONLY -> "invitation_only"
            CLOSED -> "closed"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class GroupVisibility {
    @SerialName("public") PUBLIC,
    @SerialName("unlisted") UNLISTED,
    @SerialName("private") PRIVATE,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): GroupVisibility =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            PUBLIC -> "public"
            UNLISTED -> "unlisted"
            PRIVATE -> "private"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class GroupNotificationLevel {
    @SerialName("default") DEFAULT,
    @SerialName("all") ALL,
    @SerialName("mentions") MENTIONS,
    @SerialName("muted") MUTED,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): GroupNotificationLevel =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            DEFAULT -> "default"
            ALL -> "all"
            MENTIONS -> "mentions"
            MUTED -> "muted"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class MessagingLevel {
    @SerialName("all") ALL,
    @SerialName("mentions") MENTIONS,
    @SerialName("off") OFF,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): MessagingLevel =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            ALL -> "all"
            MENTIONS -> "mentions"
            OFF -> "off"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class GroupRsvp {
    @SerialName("going") GOING,
    @SerialName("maybe") MAYBE,
    @SerialName("not_going") NOT_GOING,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): GroupRsvp =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            GOING -> "going"
            MAYBE -> "maybe"
            NOT_GOING -> "not_going"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class GroupChatState {
    @SerialName("ready") READY,
    @SerialName("read_only") READ_ONLY,
    @SerialName("unavailable") UNAVAILABLE,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): GroupChatState =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            READY -> "ready"
            READ_ONLY -> "read_only"
            UNAVAILABLE -> "unavailable"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class ChatReportReason {
    @SerialName("spam") SPAM,
    @SerialName("harassment") HARASSMENT,
    @SerialName("hate") HATE,
    @SerialName("sexual") SEXUAL,
    @SerialName("violence") VIOLENCE,
    @SerialName("self_harm") SELF_HARM,
    @SerialName("inappropriate") INAPPROPRIATE,
    @SerialName("other") OTHER,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): ChatReportReason =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            SPAM -> "spam"
            HARASSMENT -> "harassment"
            HATE -> "hate"
            SEXUAL -> "sexual"
            VIOLENCE -> "violence"
            SELF_HARM -> "self_harm"
            INAPPROPRIATE -> "inappropriate"
            OTHER -> "other"
            UNKNOWN -> "unknown"
        }
}

/**
 * Forward-compatible: an unrecognised value decodes to [UNKNOWN] rather than
 * throwing, so a server that adds a case cannot break a released build.
 */
@Serializable
enum class ChatCardKind {
    @SerialName("group_event") GROUP_EVENT,
    @SerialName("church_event") CHURCH_EVENT,
    @SerialName("sermon") SERMON,
    UNKNOWN;

    companion object {
        fun fromWire(value: String?): ChatCardKind =
            entries.firstOrNull { it.wire == value } ?: UNKNOWN
    }

    val wire: String
        get() = when (this) {
            GROUP_EVENT -> "group_event"
            CHURCH_EVENT -> "church_event"
            SERMON -> "sermon"
            UNKNOWN -> "unknown"
        }
}

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class Deprecation(
    val sunsetOn: String,
    val replacement: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class FieldIssue(
    val field: String,
    val issue: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class Meta(
    val apiVersion: String,
    val apiMajor: Int,
    val requestId: String,
    val minimumSupportedClientBuild: Int,
    val deprecation: Deprecation? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ErrorBody(
    val code: MobileErrorCode,
    val message: String,
    val retryable: Boolean,
    val fields: List<FieldIssue>? = null,
    val retryAfterSeconds: Int? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class Failure(
    val ok: Boolean,
    val error: ErrorBody,
    val meta: Meta
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class VisitorProfile(
    val displayName: String? = null,
    val avatarUrl: String? = null,
    val status: AccountStatus,
    val termsVersion: String? = null,
    val termsAcceptedAt: String? = null,
    val privacyVersion: String? = null,
    val privacyAcceptedAt: String? = null,
    val autoAttendanceConsent: ConsentState,
    val communicationPrefs: Map<String, Boolean>,
    val selectedChurchSlug: String? = null,
    val authorizationVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AppThemePalette(
    val primary: String,
    val accent: String,
    val accentSoft: String,
    val onAccent: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChurchAppTheme(
    val light: AppThemePalette,
    val dark: AppThemePalette
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChurchThemeSettings(
    val primaryColor: String? = null,
    val accentColor: String? = null,
    val appTheme: ChurchAppTheme? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class UpdateChurchThemeRequest(
    val primaryColor: String? = null,
    val accentColor: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChurchRelationship(
    val churchSlug: String,
    val churchName: String,
    val logoUrl: String? = null,
    val appTheme: ChurchAppTheme? = null,
    val canManageBranding: Boolean? = null,
    val automaticCheckInEnabled: Boolean? = null,
    val codeCheckInEnabled: Boolean? = null,
    val groupsEnabled: Boolean? = null,
    val state: RelationshipState,
    val joinPolicy: JoinPolicy,
    val joinedAt: String? = null,
    val updatedAt: String,
    val canReadPublishedContent: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AccountRequest(
    val id: String,
    val kind: AccountRequestKind,
    val status: AccountRequestStatus,
    val requestedAt: String,
    val completedAt: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PeopleClaimRequest(
    val churchSlug: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PeopleClaimResponse(
    val status: String,
    val source: String,
    val isLinked: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class Bootstrap(
    val profile: VisitorProfile,
    val relationships: List<ChurchRelationship>,
    val pendingRequests: List<AccountRequest>,
    val requiredTermsVersion: String,
    val requiredPrivacyVersion: String,
    val enabledCapabilities: List<String>,
    val serverTime: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class RelationshipPage(
    val items: List<ChurchRelationship>,
    val nextCursor: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SelectedChurch(
    val selectedChurchSlug: String? = null,
    val authorizationVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SignOutResult(
    val signedOut: Boolean,
    val authorizationVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class Health(
    val status: String,
    val apiVersion: String,
    val apiMajor: Int,
    val minimumSupportedClientBuild: Int,
    val serverTime: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class UpdateProfileRequest(
    val displayName: String? = null,
    val communicationPrefs: Map<String, Boolean>? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class UpdateProfilePhotoRequest(
    val jpegBase64: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ProfilePhotoResult(
    val avatarUrl: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class BrandingPhotoRequest(
    val imageBase64: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class BrandingPhotoResult(
    val url: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChurchBrandingState(
    val canEdit: Boolean,
    val logoUrl: String? = null,
    val coverUrl: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SelectChurchRequest(
    val churchSlug: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ConsentRequest(
    val termsVersion: String? = null,
    val privacyVersion: String? = null,
    val autoAttendanceConsent: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AccountActionRequest(
    val kind: AccountRequestKind
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class DiscoveredChurch(
    val slug: String,
    val name: String,
    val logoUrl: String? = null,
    val publicSummary: String? = null,
    val denomination: String? = null,
    val city: String? = null,
    val state: String? = null,
    val postalCode: String? = null,
    val joinPolicy: JoinPolicy,
    val publicProfileVersion: Int,
    val distanceKm: Double? = null,
    val campusName: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class DiscoveryPage(
    val items: List<DiscoveredChurch>,
    val nextCursor: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PublicCampus(
    val slug: String,
    val name: String,
    val addressLine1: String? = null,
    val city: String? = null,
    val state: String? = null,
    val postalCode: String? = null,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val timezone: String,
    val isPrimary: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PublicServiceTime(
    val campusSlug: String,
    val label: String,
    val dayOfWeek: Int,
    val startTime: String,
    val kind: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChurchSocialLink(
    val platform: String,
    val url: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChurchQuickLink(
    val label: String,
    val url: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChurchProfile(
    val slug: String,
    val name: String,
    val logoUrl: String? = null,
    val coverImageUrl: String? = null,
    val publicSummary: String? = null,
    val tagline: String? = null,
    val denomination: String? = null,
    val address: String? = null,
    val city: String? = null,
    val state: String? = null,
    val postalCode: String? = null,
    val website: String? = null,
    val phone: String? = null,
    val email: String? = null,
    val joinPolicy: JoinPolicy,
    val timezone: String,
    val publicProfileVersion: Int,
    val campuses: List<PublicCampus>,
    val serviceTimes: List<PublicServiceTime>,
    val relationshipState: RelationshipState? = null,
    val about: String? = null,
    val mapsUrl: String? = null,
    val socialLinks: List<ChurchSocialLink>? = null,
    val quickLinks: List<ChurchQuickLink>? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class OnboardingState(
    val needsOnboarding: Boolean,
    val hasAnyRelationship: Boolean,
    val selectedChurchSlug: String? = null,
    val activeChurchCount: Int,
    val requiresChurchChooser: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class FeedItem(
    val id: String,
    val title: String,
    val body: String,
    val startAt: String,
    val endAt: String? = null,
    val allDay: Boolean,
    val location: String? = null,
    val posterUrl: String? = null,
    val posterAltText: String? = null,
    val isPinned: Boolean,
    val visibility: AnnouncementVisibility,
    val publicationVersion: Int,
    val publishedAt: String? = null,
    val isEvent: Boolean,
    val churchSlug: String,
    val churchName: String,
    val churchTimezone: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class FeedPage(
    val items: List<FeedItem>,
    val nextCursor: String? = null,
    val feedVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SchedulePage(
    val items: List<FeedItem>,
    val scheduleVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class NotificationPreference(
    val churchSlug: String,
    val topic: NotificationTopic,
    val isEnabled: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class DeviceInstallation(
    val installId: String,
    val platform: DevicePlatform,
    val isEnabled: Boolean,
    val lastSeenAt: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class FollowRequest(
    val churchSlug: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AcceptInvitationRequest(
    val token: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class InvitationPreview(
    val churchSlug: String,
    val churchName: String,
    val logoUrl: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class InvitationPreviewRequest(
    val token: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class RegisterDeviceRequest(
    val installId: String,
    val platform: DevicePlatform,
    val provider: String,
    val providerToken: String,
    val apnsEnvironment: String? = null,
    val appVersion: String? = null,
    val clientBuild: Int? = null,
    val osVersion: String? = null,
    val locale: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SetPreferenceRequest(
    val churchSlug: String,
    val topic: NotificationTopic,
    val isEnabled: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class EligibleOccurrence(
    val occurrenceId: String,
    val label: String,
    val churchSlug: String,
    val campusName: String? = null,
    val localServiceDate: String,
    val timezone: String,
    val startsAt: String,
    val endsAt: String,
    val checkinOpensAt: String,
    val checkinClosesAt: String,
    val status: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceCapability(
    val occurrenceId: String,
    val geofenceEnabled: Boolean,
    val qrEnabled: Boolean,
    val manualEnabled: Boolean,
    val requiresConfirmation: Boolean,
    val minDwellSeconds: Int,
    val maxLocationAccuracyM: Int,
    val hasVerifiedPeopleLink: Boolean,
    val autoAttendanceConsent: ConsentState,
    val canAttemptAutomatically: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceResult(
    val outcome: AttendanceOutcome,
    val message: String,
    val occurrenceId: String? = null,
    val countedAt: String? = null,
    val confirmationNotBefore: String? = null,
    val detectionId: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceStatus(
    val occurrenceId: String,
    val isCounted: Boolean,
    val status: String? = null,
    val source: AttendanceSource? = null,
    val countedAt: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceHistoryItem(
    val occurrenceId: String,
    val label: String,
    val localServiceDate: String,
    val campusName: String? = null,
    val source: AttendanceSource,
    val status: String,
    val countedAt: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceHistoryPage(
    val items: List<AttendanceHistoryItem>,
    val nextCursor: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceAttemptRequest(
    val occurrenceId: String? = null,
    val source: String,
    val phase: String,
    val observedAt: String? = null,
    val accuracyMeters: Double? = null,
    val dwellSeconds: Int? = null,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val mockLocationReported: Boolean? = null,
    val attemptId: String? = null,
    val detectionId: String? = null,
    val regionId: String? = null,
    val configVersion: Int? = null,
    val qrToken: String? = null,
    val shortCode: String? = null,
    val scanAttemptId: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceConsentRequest(
    val autoAttendanceConsent: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceConsentResult(
    val autoAttendanceConsent: String,
    val authorizationVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GeofenceRegion(
    val regionId: String,
    val campusName: String,
    val latitude: Double,
    val longitude: Double,
    val radiusMeters: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GeofenceWindow(
    val occurrenceId: String,
    val label: String,
    val startsAt: String,
    val endsAt: String,
    val checkinOpensAt: String,
    val checkinClosesAt: String,
    val timezone: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class AttendanceSourceAvailability(
    val geofence: Boolean,
    val qr: Boolean,
    val manual: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GeofenceConfiguration(
    val churchSlug: String,
    val regions: List<GeofenceRegion>,
    val windows: List<GeofenceWindow>,
    val sources: AttendanceSourceAvailability,
    val requiresConfirmation: Boolean,
    val minDwellSeconds: Int,
    val maxLocationAccuracyM: Int,
    val configVersion: Int,
    val expiresAt: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GeofenceConfigResponse(
    val configuration: GeofenceConfiguration? = null,
    val refusalReason: String? = null,
    val message: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class LinkedPresentation(
    val presentationId: String,
    val sermonId: String,
    val title: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class LinkedService(
    val mediaId: String,
    val kind: String,
    val title: String,
    val startsAt: String,
    val posterUrl: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class LiveMedia(
    val presentation: LinkedPresentation? = null,
    val state: String,
    val mediaId: String,
    val kind: String,
    val title: String,
    val startsAt: String,
    val countdownEnabled: Boolean,
    val posterUrl: String? = null,
    val publicationVersion: Int,
    val churchSlug: String,
    val churchName: String,
    val churchTimezone: String,
    val replayMediaId: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class LiveMediaResponse(
    val live: LiveMedia? = null,
    val mediaVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ArchiveItem(
    val mediaId: String,
    val kind: String,
    val title: String,
    val summary: String? = null,
    val publishedAt: String,
    val recordedAt: String,
    val durationSeconds: Int? = null,
    val posterUrl: String? = null,
    val seriesName: String? = null,
    val speakers: List<String>,
    val publicationVersion: Int,
    val churchSlug: String,
    val churchName: String,
    val churchTimezone: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class MediaPage(
    val items: List<ArchiveItem>,
    val nextCursor: String? = null,
    val mediaVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class MediaDetail(
    val presentation: LinkedPresentation? = null,
    val mediaId: String,
    val kind: String,
    val title: String,
    val summary: String? = null,
    val publishedAt: String,
    val recordedAt: String,
    val durationSeconds: Int? = null,
    val startOffsetSeconds: Int,
    val posterUrl: String? = null,
    val seriesName: String? = null,
    val speakers: List<String>,
    val chapters: List<String>,
    val topics: List<String>,
    val publicationVersion: Int,
    val churchSlug: String,
    val churchName: String,
    val churchTimezone: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SermonListItem(
    val sermonId: String,
    val title: String,
    val summary: String? = null,
    val publishedAt: String,
    val preachedOn: String? = null,
    val scriptureRefs: List<String>,
    val seriesName: String? = null,
    val publicationVersion: Int,
    val churchSlug: String,
    val churchName: String,
    val churchTimezone: String,
    val theme: PresentationTheme? = null,
    val thumbnailUrl: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SermonPage(
    val items: List<SermonListItem>,
    val nextCursor: String? = null,
    val sermonVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SermonPoint(
    val title: String,
    val summary: String,
    val scripture: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SermonOutline(
    val intro: String? = null,
    val points: List<SermonPoint>,
    val application: String? = null,
    val closing: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SermonQuestion(
    val category: String,
    val question: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SermonDetail(
    val linkedServices: List<LinkedService>? = null,
    val sermonId: String,
    val title: String,
    val summary: String? = null,
    val publishedAt: String,
    val preachedOn: String? = null,
    val scriptureRefs: List<String>,
    val seriesName: String? = null,
    val publicationVersion: Int,
    val churchSlug: String,
    val churchName: String,
    val churchTimezone: String,
    val outline: SermonOutline? = null,
    val discussionQuestions: List<SermonQuestion>
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PresentationPage(
    val id: String,
    val kind: String,
    val title: String? = null,
    val body: String? = null,
    val scripture: String? = null,
    val readingOrder: List<String>
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PresentationListItem(
    val presentationId: String,
    val sermonId: String,
    val version: Int,
    val title: String,
    val publishedAt: String,
    val pageCount: Int,
    val contentHash: String,
    val scriptureRefs: List<String>,
    val seriesName: String? = null,
    val churchSlug: String,
    val churchName: String,
    val churchTimezone: String,
    val theme: PresentationTheme? = null,
    val thumbnailUrl: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PresentationPageResponse(
    val items: List<PresentationListItem>,
    val nextCursor: String? = null,
    val presentationVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PresentationTheme(
    val id: String,
    val name: String,
    val backgroundType: String,
    val bg: String? = null,
    val bgCss: String,
    val text: String,
    val accent: String,
    val fontHead: String,
    val fontBody: String,
    val italicRef: Boolean,
    val textShadow: Boolean,
    val imageUrl: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PresentationSlideRendition(
    val pageId: String,
    val imagePath: String? = null,
    val imageUrl: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PresentationRenditions(
    val slides: List<PresentationSlideRendition>,
    val pdfPath: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PresentationDetail(
    val linkedServices: List<LinkedService>? = null,
    val presentationId: String,
    val sermonId: String,
    val version: Int,
    val title: String,
    val publishedAt: String,
    val pageCount: Int,
    val contentHash: String,
    val scriptureRefs: List<String>,
    val seriesName: String? = null,
    val churchSlug: String,
    val churchName: String,
    val churchTimezone: String,
    val pages: List<PresentationPage>,
    val theme: PresentationTheme? = null,
    val renditions: PresentationRenditions
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PlaybackGrant(
    val capability: String,
    val expiresAt: String,
    val deliveryUrl: String,
    val kind: String,
    val renditionKind: String,
    val mediaId: String,
    val refreshAfterSeconds: Int,
    val startOffsetSeconds: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class PlaybackGrantRequest(
    val churchSlug: String,
    val kind: String,
    val mediaId: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GivingFund(
    val fundId: String,
    val title: String,
    val description: String? = null,
    val suggestedAmounts: List<Int>,
    val minAmountCents: Int,
    val maxAmountCents: Int,
    val currency: String,
    val publicationVersion: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GivingHome(
    val availability: String,
    val churchName: String? = null,
    val funds: List<GivingFund>,
    val recurringAvailable: Boolean,
    val givingVersion: Int,
    val applePayApproved: Boolean,
    val webGiveUrl: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class StartDonationRequest(
    val churchSlug: String,
    val fundId: String,
    val amountCents: Int,
    val clientAttemptId: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class DonationSession(
    val attemptId: String,
    val status: String,
    val clientSecret: String,
    val publishableKey: String,
    val stripeAccountId: String,
    val merchantName: String,
    val amountCents: Int,
    val currency: String,
    val fundTitle: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class DonationStatusResult(
    val attemptId: String,
    val status: String,
    val amountCents: Int,
    val currency: String,
    val fundTitle: String,
    val confirmed: Boolean,
    val occurredAt: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GivingHistoryPage(
    val items: List<DonationStatusResult>,
    val nextCursor: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GivingReceipt(
    val attemptId: String,
    val amountCents: Int,
    val currency: String,
    val fundTitle: String,
    val churchName: String,
    val paidAt: String,
    val giftType: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class StartRecurringGiftRequest(
    val churchSlug: String,
    val fundId: String,
    val amountCents: Int,
    val interval: String,
    val clientAttemptId: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class RecurringGiftSession(
    val attemptId: String,
    val clientSecret: String? = null,
    val publishableKey: String,
    val stripeAccountId: String,
    val merchantName: String,
    val amountCents: Int,
    val currency: String,
    val interval: String,
    val fundTitle: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class RecurringGift(
    val subscriptionId: String,
    val fundTitle: String,
    val amountCents: Int,
    val currency: String,
    val interval: String,
    val status: String,
    val startedAt: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class RecurringGiftList(
    val items: List<RecurringGift>
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class RecurringGiftCancelResult(
    val subscriptionId: String,
    val stopped: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupTypeSummary(
    val id: String,
    val name: String,
    val icon: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupLeader(
    val name: String,
    val avatarUrl: String? = null,
    val groupRole: String,
    val chatUserId: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupEventSummary(
    val id: String,
    val groupId: String,
    val title: String,
    val startsAt: String,
    val endsAt: String,
    val timezone: String,
    val locationName: String? = null,
    val isCancelled: Boolean,
    val rsvp: String? = null,
    val goingCount: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupChatInfo(
    val cid: String,
    val channelType: String,
    val channelId: String,
    val state: String,
    val postingPolicy: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupSummary(
    val id: String,
    val name: String,
    val summary: String? = null,
    val coverImageUrl: String? = null,
    val type: GroupTypeSummary? = null,
    val memberCount: Int,
    val capacity: Int? = null,
    val enrollment: String,
    val visibility: String,
    val status: String,
    val scheduleText: String? = null,
    val meetingDays: List<Int>,
    val campusName: String? = null,
    val locationName: String? = null,
    val nextEvent: GroupEventSummary? = null,
    val membershipState: String,
    val groupRole: String? = null,
    val joinAction: String,
    val chat: GroupChatInfo? = null,
    val isYouth: Boolean,
    val version: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class MyGroups(
    val items: List<GroupSummary>,
    val directMessagesEnabled: Boolean,
    val messagingAvailable: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupDiscoveryPage(
    val items: List<GroupSummary>,
    val nextCursor: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupCampusOption(
    val id: String,
    val name: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupFilters(
    val types: List<GroupTypeSummary>,
    val campuses: List<GroupCampusOption>,
    val days: List<Int>
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupCapabilities(
    val canViewMembers: Boolean,
    val canManageMembers: Boolean,
    val canManageRequests: Boolean,
    val canInvite: Boolean,
    val canManageRoles: Boolean,
    val canEditDetails: Boolean,
    val canManageEvents: Boolean,
    val canTakeAttendance: Boolean,
    val canModerateChat: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupSchedule(
    val text: String,
    val frequency: String,
    val dayOfWeek: Int,
    val startTime: String,
    val durationMinutes: Int,
    val timezone: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupLocation(
    val name: String? = null,
    val address: String? = null,
    val onlineMeetingUrl: String? = null,
    val membersOnly: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupDetail(
    val group: GroupSummary,
    val description: String? = null,
    val leaders: List<GroupLeader>,
    val schedules: List<GroupSchedule>,
    val location: GroupLocation? = null,
    val upcomingEvents: List<GroupEventSummary>,
    val capabilities: GroupCapabilities,
    val pendingRequestCount: Int,
    val notificationLevel: String? = null,
    val isArchived: Boolean,
    val chatPosting: String? = null,
    val memberListVisibility: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class JoinGroupRequest(
    val message: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class UpdateGroupDetailsRequest(
    val expectedVersion: Int,
    val name: String,
    val description: String? = null,
    val enrollment: String,
    val capacity: Int? = null,
    val locationName: String? = null,
    val locationAddress: String? = null,
    val onlineMeetingUrl: String? = null,
    val chatPosting: String,
    val memberListVisibility: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupJoinResult(
    val outcome: String,
    val group: GroupSummary? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupMember(
    val membershipId: String,
    val name: String,
    val avatarUrl: String? = null,
    val groupRole: String,
    val joinedAt: String,
    val chatUserId: String? = null,
    val isYou: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupMemberPage(
    val items: List<GroupMember>,
    val nextCursor: String? = null,
    val total: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupJoinRequestItem(
    val requestId: String,
    val name: String,
    val avatarUrl: String? = null,
    val message: String? = null,
    val requestedAt: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupJoinRequestPage(
    val items: List<GroupJoinRequestItem>,
    val nextCursor: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class DecideGroupRequest(
    val decision: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupCommandResult(
    val outcome: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SetGroupRoleRequest(
    val groupRole: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class RemoveGroupMemberRequest(
    val ban: Boolean,
    val reason: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupInvitation(
    val url: String,
    val expiresAt: String,
    val maxUses: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupInvitationTokenRequest(
    val token: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupInvitationPreview(
    val groupId: String,
    val groupName: String,
    val coverImageUrl: String? = null,
    val churchSlug: String,
    val churchName: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupEventRsvpCounts(
    val going: Int,
    val maybe: Int,
    val notGoing: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupEventAttendanceSummary(
    val taken: Boolean,
    val present: Int,
    val absent: Int,
    val guests: Int,
    val firstTimeGuests: Int
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupEventDetail(
    val event: GroupEventSummary,
    val groupName: String,
    val description: String? = null,
    val locationAddress: String? = null,
    val onlineMeetingUrl: String? = null,
    val rsvpCounts: GroupEventRsvpCounts,
    val attendance: GroupEventAttendanceSummary? = null,
    val canEdit: Boolean,
    val canTakeAttendance: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupEventPage(
    val items: List<GroupEventSummary>,
    val nextCursor: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class UpsertGroupEventRequest(
    val title: String,
    val description: String? = null,
    val startsAt: String,
    val endsAt: String,
    val timezone: String? = null,
    val locationName: String? = null,
    val locationAddress: String? = null,
    val onlineMeetingUrl: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupEventRsvpRequest(
    val response: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupAttendanceEntry(
    val membershipId: String,
    val name: String,
    val avatarUrl: String? = null,
    val groupRole: String,
    val present: Boolean,
    val recordable: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupAttendanceSheet(
    val eventId: String,
    val title: String,
    val startsAt: String,
    val timezone: String,
    val taken: Boolean,
    val entries: List<GroupAttendanceEntry>,
    val presentCount: Int,
    val absentCount: Int,
    val guestCount: Int,
    val firstTimeGuestCount: Int,
    val notes: String? = null,
    val recordableUntil: String,
    val canRecord: Boolean,
    val lockedReason: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SubmitGroupAttendanceRequest(
    val presentMembershipIds: List<String>,
    val guestCount: Int,
    val firstTimeGuestCount: Int,
    val notes: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChatSession(
    val appKey: String,
    val churchTeam: String,
    val chatUserId: String,
    val userToken: String,
    val expiresAt: String,
    val suspended: Boolean,
    val suspendedUntil: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChatRoute(
    val kind: String,
    val churchSlug: String,
    val groupId: String? = null,
    val cid: String,
    val messageId: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class GroupNotificationSetting(
    val groupId: String,
    val groupName: String,
    val level: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class MessagingPreferences(
    val level: String,
    val groups: List<GroupNotificationSetting>
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SetMessagingLevelRequest(
    val level: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class SetGroupNotificationRequest(
    val level: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class MessagingContact(
    val chatUserId: String,
    val name: String,
    val avatarUrl: String? = null,
    val context: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class MessagingContactPage(
    val items: List<MessagingContact>,
    val nextCursor: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class StartDirectMessageRequest(
    val chatUserId: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class DirectConversation(
    val cid: String,
    val channelId: String,
    val state: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChatReportRequest(
    val cid: String,
    val messageId: String? = null,
    val reportedChatUserId: String? = null,
    val reason: String,
    val details: String? = null
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChatReportResult(
    val received: Boolean
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChatBlockRequest(
    val chatUserId: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChatBlockedPerson(
    val chatUserId: String,
    val name: String,
    val blockedAt: String
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChatBlockList(
    val items: List<ChatBlockedPerson>
)

/**
 * Unknown additive fields are ignored by the configured Json instance,
 * which is what lets a released client keep working when the server adds one.
 */
@Serializable
data class ChatCard(
    val kind: String,
    val id: String,
    val available: Boolean,
    val title: String? = null,
    val subtitle: String? = null,
    val imageUrl: String? = null,
    val startsAt: String? = null,
    val endsAt: String? = null,
    val locationName: String? = null,
    val deepLink: String? = null
)

