"use client";
import { useState } from "react";
import { CalendarDays, Check, MapPin, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { AttendanceSheet } from "@/lib/groups/gatherings";
import type { StaffGroupDetail } from "@/lib/groups/staff/groups";
import type { listStaffGatherings, getStaffGathering } from "@/lib/groups/staff/gatherings";
import * as actions from "@/app/dashboard/groups/actions";
import { dateTime, Empty, Field, Modal, Notice, Pill, Submit, useGroupAction } from "./shared";

type Gathering = Awaited<ReturnType<typeof listStaffGatherings>>["items"][number];
type EventPage = Awaited<ReturnType<typeof listStaffGatherings>>;
type EventDetail = NonNullable<Awaited<ReturnType<typeof getStaffGathering>>>;
export function Gatherings({ detail, upcoming, past, timezone }: { detail: StaffGroupDetail; upcoming: EventPage; past: EventPage; timezone: string }) {
  const [mode, setMode] = useState<"upcoming" | "past">("upcoming");
  const [editing, setEditing] = useState<EventDetail | null>(null);
  const [extra, setExtra] = useState<Partial<Record<"upcoming" | "past", EventPage>>>({}); const [adding, setAdding] = useState(false); const [cancelling, setCancelling] = useState<Gathering | null>(null); const [sheet, setSheet] = useState<AttendanceSheet | null>(null);
  const { pending, error, run } = useGroupAction(); const archived = detail.group.status === "archived";
  const initial = mode === "upcoming" ? upcoming : past;
  const items = [...initial.items, ...(extra[mode]?.items ?? []).filter(e => !initial.items.some(i => i.id === e.id))];
  const cursor = extra[mode] ? extra[mode]?.nextCursor : initial.nextCursor;
  return <><div className="g-toolbar"><div className="g-segment">{(["upcoming", "past"] as const).map(s => <button key={s} className={mode === s ? "is-active" : ""} aria-pressed={mode === s} onClick={() => setMode(s)}>{s === "upcoming" ? "Coming up" : "Past gatherings"}</button>)}</div>{!archived && <Button onClick={() => setAdding(true)}><Plus className="size-4" />Plan a gathering</Button>}</div>{error && <Notice>{error}</Notice>}{items.length ? <div className="g-panel">{items.map(event => <div className="g-row" key={event.id}><div className="flex min-w-0 gap-4"><div className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-muted"><CalendarDays className="size-5 text-muted-foreground" /></div><div><div className="g-row-title">{event.title} {event.isCancelled && <Pill>Cancelled</Pill>}</div><p className="g-row-sub">{dateTime(event.startsAt, event.timezone)}</p>{event.locationName && <p className="g-meta mt-1"><MapPin />{event.locationName}</p>}<p className="g-row-sub">{event.attendance ? `${event.attendance.present} present · ${event.attendance.guests} guests` : `${event.goingCount} planning to come`}</p></div></div><div className="flex flex-wrap gap-2">{!event.isCancelled && <><Button size="sm" variant="outline" disabled={pending} onClick={() => run(() => actions.attendanceSheet(detail.group.id, event.id), undefined, setSheet)}>{event.attendance ? "View attendance" : "Take attendance"}</Button>{!archived && <Button size="sm" variant="ghost" disabled={pending} onClick={() => run(() => actions.gatheringDetails(detail.group.id, event.id), undefined, data => { if (data) setEditing(data); })}>Edit</Button>}{mode === "upcoming" && !archived && <Button size="sm" variant="ghost" onClick={() => setCancelling(event)}>Cancel gathering</Button>}</>}</div></div>)}</div> : <Empty icon="events" title={mode === "upcoming" ? "Make time for each other" : "Your story is just beginning"} description={mode === "upcoming" ? "Plan the next get-together, or set a repeating schedule so everyone knows when to come." : "Past gatherings and attendance will appear here."} />}
    {cursor && <Button variant="outline" className="mt-4" disabled={pending} onClick={() => run(() => actions.moreGatherings(detail.group.id, mode, cursor), undefined, page => setExtra(old => ({ ...old, [mode]: { items: [...(old[mode]?.items ?? []), ...page.items], nextCursor: page.nextCursor } })))}>Show more gatherings</Button>}
    <Modal open={!!editing} onClose={() => setEditing(null)} title="Edit gathering">{editing && <GatheringForm groupId={detail.group.id} timezone={timezone} existing={editing} close={() => { setEditing(null); setExtra({}); }} />}</Modal>
    <Modal open={adding} onClose={() => setAdding(false)} title="Plan a gathering" description="Give everyone something to look forward to.">{adding && <GatheringForm groupId={detail.group.id} timezone={timezone} close={() => setAdding(false)} />}</Modal>
    <Modal open={!!cancelling} onClose={() => setCancelling(null)} title="Cancel this gathering?" description="Members will be notified. The gathering will remain in your history.">{cancelling && <form onSubmit={e => { e.preventDefault(); const reason = String(new FormData(e.currentTarget).get("reason") ?? ""); run(() => actions.cancelGathering(detail.group.id, cancelling.id, reason), "Gathering cancelled", () => setCancelling(null)); }}><Field label="Let people know why (optional)"><textarea name="reason" rows={3} maxLength={300} /></Field>{error && <Notice>{error}</Notice>}<div className="g-form-actions"><Button type="submit" variant="destructive" disabled={pending}>Cancel gathering</Button></div></form>}</Modal>
    <Modal open={!!sheet} onClose={() => setSheet(null)} title={sheet?.title ?? "Attendance"} description={sheet ? dateTime(sheet.startsAt, sheet.timezone) : undefined}>{sheet && <Attendance groupId={detail.group.id} sheet={sheet} close={() => setSheet(null)} />}</Modal>
  </>;
}
function GatheringForm({ groupId, timezone, close, existing }: { groupId: string; timezone: string; close: () => void; existing?: EventDetail }) {
  const { pending, error, run } = useGroupAction();
  const localZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const localTime = (value?: string) => { if (!value) return ""; const d = new Date(value); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16); };
  return <form className="space-y-4" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); run(() => actions.saveGathering(groupId, existing?.event.id ?? null, { title: String(f.get("title")), description: String(f.get("description")), startsAt: new Date(String(f.get("starts"))).toISOString(), endsAt: new Date(String(f.get("ends"))).toISOString(), timezone: localZone, locationName: String(f.get("location")), onlineMeetingUrl: String(f.get("url")) }), existing ? "Gathering updated" : "Gathering planned", close); }}><Field label="What’s the occasion?"><input autoFocus name="title" defaultValue={existing?.event.title} required maxLength={120} placeholder="e.g. Dinner & discussion" /></Field><div className="g-form-grid"><Field label="Starts"><input name="starts" type="datetime-local" defaultValue={localTime(existing?.event.startsAt)} required /></Field><Field label="Ends"><input name="ends" type="datetime-local" defaultValue={localTime(existing?.event.endsAt)} required /></Field></div><p className="text-xs text-muted-foreground">Times are entered in {localZone}.{localZone !== timezone && ` Your church’s time zone is ${timezone}.`}</p><Field label="Where"><input name="location" defaultValue={existing?.event.locationName ?? ""} maxLength={200} placeholder="e.g. The fellowship hall" /></Field><Field label="Online meeting link (optional)"><input name="url" defaultValue={existing?.onlineMeetingUrl ?? ""} type="url" placeholder="https://" /></Field><Field label="Anything to know? (optional)"><textarea name="description" defaultValue={existing?.description ?? ""} rows={3} maxLength={4000} placeholder="What to bring, what to expect…" /></Field>{error && <Notice>{error}</Notice>}<div className="g-form-actions"><Submit pending={pending}>{existing ? "Save changes" : "Plan gathering"}</Submit></div></form>;
}
function Attendance({ groupId, sheet, close }: { groupId: string; sheet: AttendanceSheet; close: () => void }) {
  const [selected, setSelected] = useState(sheet.entries.filter(e => e.present).map(e => e.membershipId)); const [key] = useState(() => crypto.randomUUID());
  const { pending, error, run } = useGroupAction();
  return <form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); run(() => actions.recordAttendance(groupId, sheet.eventId, { presentMembershipIds: selected, guestCount: Number(f.get("guests")), firstTimeGuestCount: Number(f.get("first")), notes: String(f.get("notes")) }, key), "Attendance saved", close); }}><div className="mb-3 flex items-center justify-between"><span className="text-sm font-semibold">{selected.length} present</span><Button variant="ghost" size="sm" onClick={() => setSelected(selected.length ? [] : sheet.entries.filter(e => e.recordable).map(e => e.membershipId))}>{selected.length ? "Clear selection" : "Mark everyone present"}</Button></div><div className="max-h-64 overflow-y-auto">{sheet.entries.map(entry => <label key={entry.membershipId} className="g-row cursor-pointer"><span className="text-sm">{entry.name}{!entry.recordable && <small className="block text-muted-foreground">No longer on the roster</small>}</span><input type="checkbox" disabled={!entry.recordable || pending} checked={selected.includes(entry.membershipId)} onChange={e => setSelected(s => e.target.checked ? [...s, entry.membershipId] : s.filter(id => id !== entry.membershipId))} className="size-5" /></label>)}</div><div className="g-form-grid mt-5"><Field label="Guests"><input type="number" name="guests" min={0} max={1000} defaultValue={sheet.guestCount} required /></Field><Field label="First-time guests"><input type="number" name="first" min={0} max={1000} defaultValue={sheet.firstTimeGuestCount} required /></Field></div><div className="mt-4"><Field label="Leader notes (optional)"><textarea name="notes" rows={2} maxLength={1000} defaultValue={sheet.notes ?? ""} /></Field></div>{error && <Notice>{error}</Notice>}<div className="g-form-actions"><Submit pending={pending}>Save attendance</Submit></div></form>;
}
export function Schedules({ detail, timezone }: { detail: StaffGroupDetail; timezone: string }) {
  const [adding, setAdding] = useState(false); const { pending, error, run } = useGroupAction();
  return <div className="g-panel"><div className="g-panel-head"><div><h3>Find your rhythm</h3><p className="g-row-sub">Repeating schedules keep the next gathering on the calendar.</p></div><Button variant="outline" size="sm" onClick={() => setAdding(true)}><Plus className="size-4" />Add schedule</Button></div>{detail.schedules.filter(s => s.isActive).map(s => <div key={s.id} className="g-row"><div><p className="g-row-title">{s.description}</p><p className="g-row-sub">{s.durationMinutes} minutes · {s.timezone}</p></div><Button size="sm" variant="ghost" disabled={pending} onClick={() => run(() => actions.stopSchedule(detail.group.id, s.id), "Schedule stopped")}>Stop repeating</Button></div>)}{error && <Notice>{error}</Notice>}{detail.schedules.some(s => s.isActive) && <Button variant="ghost" className="mt-4" disabled={pending} onClick={() => run(() => actions.generateGatherings(detail.group.id), "Upcoming gatherings updated")}><Check className="size-4" />Fill the next 8 weeks</Button>}
    <Modal open={adding} onClose={() => setAdding(false)} title="A regular time together"><form className="space-y-4" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); run(() => actions.saveSchedule(detail.group.id, null, { frequency: String(f.get("frequency")), dayOfWeek: Number(f.get("day")), weekOfMonth: f.get("frequency") === "monthly" ? Number(f.get("week")) : null, startTime: String(f.get("time")), durationMinutes: Number(f.get("duration")), timezone: String(f.get("timezone")), startsOn: String(f.get("starts")), endsOn: String(f.get("ends")) || null }), "Schedule saved", () => setAdding(false)); }}><div className="g-form-grid"><Field label="Repeat"><select name="frequency"><option value="weekly">Every week</option><option value="biweekly">Every other week</option><option value="monthly">Every month</option></select></Field><Field label="Day"><select name="day">{["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"].map((d, i) => <option value={i} key={d}>{d}</option>)}</select></Field><Field label="Week (monthly schedules)"><select name="week">{[[1,"First"],[2,"Second"],[3,"Third"],[4,"Fourth"],[-1,"Last"]].map(([v,t]) => <option key={v} value={v}>{t}</option>)}</select></Field><Field label="Time"><input name="time" type="time" required defaultValue="18:30" /></Field><Field label="Duration in minutes"><input name="duration" type="number" min={15} max={720} defaultValue={90} required /></Field><Field label="Time zone"><input name="timezone" defaultValue={timezone} required /></Field><Field label="Start date"><input name="starts" type="date" required /></Field><Field label="End date (optional)"><input name="ends" type="date" /></Field></div>{error && <Notice>{error}</Notice>}<div className="g-form-actions"><Submit pending={pending}>Save schedule</Submit></div></form></Modal>
  </div>;
}
