"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, type ReactNode } from "react";
import { CalendarDays, ImagePlus, MapPin, ShieldCheck, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { StaffGroupDetail, StaffGroupType } from "@/lib/groups/staff/groups";
import { lifecycle } from "@/app/dashboard/groups/actions";
import { Avatar, BackLink, base, Field, GroupAvatar, GroupBackdrop, label, Modal, Notice, Pill, useGroupAction } from "./shared";
import { GroupFormButton } from "./group-form";
export function GroupDetailShell({ detail, tab, types, campuses, children }: { detail: StaffGroupDetail; tab: string; types: StaffGroupType[]; campuses: { id: string; name: string }[]; children: ReactNode }) {
  const g = detail.group;
  return <><BackLink /><section className="g-group-hero"><GroupBackdrop url={g.cover_image_url} /><div className="g-group-hero-row"><GroupAvatar name={g.name} url={g.cover_image_url} size={116} /><div className="min-w-0 flex-1"><div className="mb-3 flex flex-wrap gap-2"><Pill>{detail.type?.name ?? "Community"}</Pill><Pill tone={g.status === "active" ? "green" : "neutral"}>{label(g.status)}</Pill>{g.safety_profile === "youth" && <Pill><ShieldCheck className="size-3" />Youth group</Pill>}</div><h1>{g.name}</h1><p className="g-meta mt-3"><UsersRound />{g.member_count} members{detail.campus && ` · ${detail.campus.name}`}</p></div>{g.status === "active" && <div className="g-group-hero-actions"><Link className="g-photo-link" href={`${base}/${g.id}/settings#photo`}><ImagePlus className="size-4" />{g.cover_image_url ? "Change photo" : "Add a photo"}</Link><GroupFormButton detail={detail} types={types} campuses={campuses} /></div>}</div></section>{g.status === "archived" && <Notice>This group is archived. Members can read its conversation history. Restore it to welcome people and plan gatherings again.</Notice>}<nav className="g-detail-tabs" aria-label="Group sections">{["overview", "chat", "members", "gatherings", "requests", "settings"].map(t => <Link key={t} href={`${base}/${g.id}${t === "overview" ? "" : `/${t}`}`} aria-current={tab === t ? "page" : undefined}>{label(t)}{t === "requests" && g.pending_request_count > 0 && ` (${g.pending_request_count})`}</Link>)}</nav>{children}</>;
}
export function GroupOverview({ detail, children }: { detail: StaffGroupDetail; children?: ReactNode }) {
  const g = detail.group;
  return <div className="g-detail-grid"><div className="space-y-6"><div className="g-panel"><h2>A little about us</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{g.description || "Every group has a story. Add a description to help people feel at home before they arrive."}</p><div className="mt-6 flex flex-wrap gap-2"><Pill>{g.enrollment === "approval_required" ? "Ask to join" : label(g.enrollment)}</Pill><Pill>{g.visibility === "public" ? "Discoverable" : label(g.visibility)}</Pill>{g.capacity && <Pill>{Math.max(0, g.capacity - g.member_count)} spots available</Pill>}</div></div>{children}</div><aside className="space-y-5"><div className="g-panel"><h3>Your group leaders</h3>{detail.leaders.length ? detail.leaders.map(l => <div className="g-row" key={l.membershipId}><span className="flex items-center gap-3"><Avatar name={l.name} /><span><strong className="g-row-title">{l.name}</strong><span className="g-row-sub block">{label(l.role)}</span></span></span></div>) : <p className="g-row-sub mt-3">Assign a leader from the Members tab to help this group flourish.</p>}</div><div className="g-panel"><h3>When & where</h3><div className="mt-5 space-y-4"><p className="g-meta"><CalendarDays />{detail.schedules.find(s => s.isActive)?.description ?? "A meeting rhythm is taking shape"}</p><p className="g-meta"><MapPin />{g.location_name ?? "Location to be announced"}</p>{g.location_address && <p className="text-xs leading-6 text-muted-foreground">{g.location_address}<br />{g.location_visibility === "members" ? "Address visible to members only" : "Public address"}</p>}{g.online_meeting_url && <a className="g-text-link" href={g.online_meeting_url} target="_blank" rel="noopener noreferrer">Open online meeting ↗</a>}</div></div></aside></div>;
}
export function GroupLifecycle({ detail }: { detail: StaffGroupDetail }) {
  const [intent, setIntent] = useState<"active" | "archived" | "deleted" | null>(null); const { pending, error, run } = useGroupAction(); const router = useRouter();
  return <div className="g-panel"><h3>{detail.group.status === "archived" ? "Ready for a new season?" : "When a season comes to a close"}</h3><p className="g-row-sub">Archiving keeps the group’s history and makes chat read-only. You can restore it later.</p><div className="mt-5 flex flex-wrap gap-3">{detail.group.status === "active" ? <Button variant="outline" onClick={() => setIntent("archived")}>Archive group</Button> : <><Button onClick={() => setIntent("active")}>Restore group</Button><Button variant="destructive" onClick={() => setIntent("deleted")}>Delete permanently</Button></>}</div><Modal open={!!intent} onClose={() => setIntent(null)} title={intent === "deleted" ? "Delete this group permanently?" : intent === "archived" ? "Archive this group?" : "Restore this group?"} description={intent === "deleted" ? "The group and its chat will be permanently removed. This cannot be undone." : intent === "archived" ? "Future gatherings will be cancelled. Conversation history remains available to existing members." : "Members can participate again. Review your meeting schedule to plan future gatherings."}><form onSubmit={e => { e.preventDefault(); const name = String(new FormData(e.currentTarget).get("confirmation") ?? ""); if (intent) run(() => lifecycle(detail.group.id, intent, name), "Group updated", () => { setIntent(null); router.push(base); }); }}>{intent === "deleted" && <Field label={`Type “${detail.group.name}” to confirm`}><input autoFocus name="confirmation" required autoComplete="off" /></Field>}{error && <Notice>{error}</Notice>}<div className="g-form-actions"><Button variant="ghost" onClick={() => setIntent(null)} disabled={pending}>Cancel</Button><Button type="submit" variant={intent === "deleted" ? "destructive" : "default"} disabled={pending}>{pending ? "Updating…" : intent === "deleted" ? "Delete permanently" : intent === "archived" ? "Archive group" : "Restore group"}</Button></div></form></Modal></div>;
}
